# Generated by Django 4.1.3 on 2022-11-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0002_rename_profile_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
