# Generated by Django 4.1.3 on 2022-11-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0004_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'ordering': ['created']},
        ),
    ]
