# Generated by Django 4.1.3 on 2022-11-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('przepisy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Przepis',
        ),
    ]
