# Generated by Django 4.1.3 on 2022-11-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('przepisy', '0002_rename_project_przepis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Przepis',
        ),
    ]
