# Generated by Django 4.1.3 on 2022-11-17 16:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('przepisy', '0005_cokolwiek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('value', models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cokolwiek',
        ),
        migrations.AddField(
            model_name='przepis',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='przepis',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ocena',
            name='przepis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='przepisy.przepis'),
        ),
        migrations.AddField(
            model_name='przepis',
            name='tags',
            field=models.ManyToManyField(blank=True, to='przepisy.tag'),
        ),
    ]
