# Generated by Django 4.1.3 on 2022-11-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0003_profil_username'),
        ('przepisy', '0007_przepis_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='przepis',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uzytkownicy.profil'),
        ),
    ]
