# Generated by Django 4.1.3 on 2022-11-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0003_profil_username'),
        ('przepisy', '0008_przepis_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='przepis',
            options={'ordering': ['vote_ratio', 'vote_total']},
        ),
        migrations.AddField(
            model_name='ocena',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uzytkownicy.profil'),
        ),
        migrations.AlterUniqueTogether(
            name='ocena',
            unique_together={('owner', 'przepis')},
        ),
    ]
