# Generated by Django 4.1.3 on 2022-11-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('przepisy', '0009_alter_przepis_options_ocena_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='przepis',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
