# Generated by Django 4.1.3 on 2022-11-22 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0004_message'),
        ('przepisy', '0010_alter_przepis_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przepis',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uzytkownicy.profil'),
        ),
    ]
