# Generated by Django 4.1.3 on 2022-12-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przepisy', '0011_alter_przepis_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='przepis',
            name='is_original',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
