# Generated by Django 4.1.3 on 2022-12-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przepisy', '0012_przepis_is_original'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='przepis',
            options={'ordering': ['-is_original', '-vote_ratio', '-vote_total', 'title']},
        ),
        migrations.AddField(
            model_name='przepis',
            name='was_asked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
